# Generated by Django 6.0.6 on 2026-07-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing')], default='IT', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
